sources:
  include:
    - ../../AetherXWatch/Sources
  exclude:
    - ../../AetherXWatch/Sources/Mocks
templates:
  - AutoMockable.stencil
output:
  ../../AetherXWatch/Sources/Mocks/Generated/GeneratedMocks.swift
