#!/usr/bin/env bash
# Builds matrix-rust-sdk for watchOS into Packages/MatrixRustSDK, then describes the build in
# Packages/MatrixRustSDK/SDKBuild.xcconfig (included by Config/Base.xcconfig).
# Works with the fork's default `watchos-http-transport` (upstream candidate: arm64 watches only, Sentry
# compiled in but never initialised) and `watchos-http-transport-arm64_32` (all watches, no Sentry).
#
# Usage: Tools/build-sdk.sh [--dev] [--arm64-only]
#   --dev         simulator only, `dev` profile.
#   --arm64-only  simulator + arm64 watches (Series 9 and later, Ultra 2 and later), no arm64_32.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SDK="${MATRIX_RUST_SDK_PATH:-$ROOT/../matrix-rust-sdk}"
PACKAGE="$ROOT/Packages/MatrixRustSDK"

export PATH="$HOME/.cargo/bin:/opt/homebrew/bin:$PATH"
export DEVELOPER_DIR="${DEVELOPER_DIR:-/Applications/Xcode.app/Contents/Developer}"
# aws-lc (reqwest's TLS, which the watch never uses: all traffic goes through URLSession) needs two
# fixes for arm64_32, applied to that target only:
# - Its cmake builder maps arm64_32-apple-watchos to CMAKE_OSX_ARCHITECTURES=arm64 (it only looks at
#   CARGO_CFG_TARGET_ARCH, "aarch64" for both watchOS device targets), so the objects fail to lipo
#   with the real arm64 slice. The toolchain file sets the Apple CMake variables correctly.
# - Its assembly mixes 64-bit limbs with arm64_32's 32-bit words. The toolchain file also turns on
#   OPENSSL_NO_ASM. Don't use AWS_LC_SYS_NO_ASM instead: it only allows opt-level 0, which the
#   SDK's reldbg profile doesn't give dependencies.
# The cc builder ignores the toolchain file, so force the cmake one for arm64_32.
export AWS_LC_SYS_CMAKE_BUILDER_arm64_32_apple_watchos=1
export CMAKE_TOOLCHAIN_FILE_arm64_32_apple_watchos="$ROOT/Tools/watchos-arm64_32.toolchain.cmake"

DEV=false
ARM64_ONLY=false
for arg in "$@"; do
  case "$arg" in
    --dev) DEV=true ;;
    --arm64-only) ARM64_ONLY=true ;;
    *) echo "Unknown option: $arg" >&2; exit 1 ;;
  esac
done

# arm64_32 only builds with the fork's constant_time_eq patch.
if [[ "$DEV" == false && "$ARM64_ONLY" == false && ! -d "$SDK/contrib/patches/constant_time_eq" ]]; then
  echo "Note: this SDK has no constant_time_eq patch, so arm64_32 can't build. Building for arm64 watches only (Series 9 and later, Ultra 2 and later)."
  ARM64_ONLY=true
fi

if [[ "$DEV" == true ]]; then
  PROFILE=dev
  TARGETS=(--target aarch64-apple-watchos-sim)
elif [[ "$ARM64_ONLY" == true ]]; then
  PROFILE=reldbg
  TARGETS=(--target aarch64-apple-watchos-sim --target aarch64-apple-watchos)
else
  PROFILE=reldbg
  TARGETS=(--target aarch64-apple-watchos-sim --target aarch64-apple-watchos --target arm64_32-apple-watchos)
fi

# --features "" drops Sentry, which would open its own sockets. Only the fork's xtask has the option.
FEATURES=()
if grep -q "features: Option<String>" "$SDK/xtask/src/swift.rs"; then
  FEATURES=(--features "")
else
  echo "Note: this SDK's xtask can't choose features, so its defaults are built in, including Sentry. The app never initialises Sentry, so it opens no sockets."
fi

cd "$SDK"
echo "Building $(git rev-parse --short HEAD) ($(git branch --show-current)) with profile $PROFILE"
cargo xtask swift build-framework \
  --profile "$PROFILE" \
  "${TARGETS[@]}" \
  ${FEATURES[@]+"${FEATURES[@]}"} \
  --watchos-deployment-target 11.0 \
  --sequentially \
  --components-path "$PACKAGE"

# Tells the app what was built: Sentry's extra TracingConfiguration field, and which device archs to link.
write_build_xcconfig() {
  local bindings="$PACKAGE/Sources/MatrixRustSDK/matrix_sdk_ffi.swift"
  local device_library
  device_library="$(find "$PACKAGE/MatrixSDKFFI.xcframework" -path "*/watchos-arm64*" ! -path "*simulator*" -name "*.a" | head -n 1)"

  echo "// Generated by Tools/build-sdk.sh from matrix-rust-sdk $(git rev-parse --short HEAD) ($(git branch --show-current)). Don't edit."
  if awk '/^public struct TracingConfiguration/,/^}/' "$bindings" | grep -q "sentryConfig"; then
    echo "SWIFT_ACTIVE_COMPILATION_CONDITIONS = \$(inherited) MATRIX_SDK_SENTRY"
  fi
  if [[ -n "$device_library" ]] && ! lipo -archs "$device_library" | grep -q "arm64_32"; then
    echo "ARCHS[sdk=watchos*] = arm64"
  fi
}
write_build_xcconfig > "$PACKAGE/SDKBuild.xcconfig"

echo "SDK ready in $PACKAGE, with SDKBuild.xcconfig:"
cat "$PACKAGE/SDKBuild.xcconfig"
